export const hobbies = [
    "Soccer",
    "Basketball",
    "Tennis",
    "Running",
    "Cycling",
    "Swimming",
    "Hiking",
    "Yoga",
    "Martial Arts",
    "Rock Climbing",
    "Gymnastics",
    "Drawing",
    "Painting",
    "Sculpting",
    "Knitting",
    "Crocheting",
    "Sewing",
    "Origami",
    "Calligraphy",
    "Pottery",
    "Woodworking",
    "Playing Instruments",
    "Singing",
    "Composing",
    "DJing",
    "Music Production",
    "Collecting Vinyl Records",
    "Attending Concerts",
    "Music Appreciation",
    "Karaoke",
    "Band Participation",
    "Camping",
    "Fishing",
    "Bird Watching",
    "Gardening",
    "Stargazing",
    "Geocaching",
    "Kayaking",
    "Sailing",
    "Picnicking",
    "Nature Walks",
    "Stamps",
    "Coins",
    "Antiques",
    "Action Figures",
    "Comic Books",
    "Postcards",
    "Rocks and Minerals",
    "Trading Cards",
    "Vintage Clothing",
    "Art",
    "Video Games",
    "Board Games",
    "Card Games",
    "Puzzle Games",
    "Role-Playing Games",
    "Arcade Games",
    "Chess",
    "Tabletop Games",
    "Esports",
    "Escape Rooms",
    "Programming",
    "Robotics",
    "Electronics",
    "3D Printing",
    "Drone Flying",
    "Virtual Reality",
    "Home Automation",
    "Gadget Collecting",
    "Tech Blogging",
    "App Development",
    "Reading Books",
    "Writing",
    "Poetry",
    "Book Club Participation",
    "Journaling",
    "Blogging",
    "Screenwriting",
    "Comic Book Reading",
    "Fan Fiction",
    "Literary Analysis",
    "Cooking",
    "Baking",
    "Wine Tasting",
    "Brewing Beer",
    "Mixology",
    "Food Tasting",
    "Vegetable Gardening",
    "Restaurant Hopping",
    "Cake Decorating",
    "Culinary Arts",
    "Yoga",
    "Pilates",
    "Meditation",
    "Weightlifting",
    "Running",
    "Cycling",
    "Dance",
    "Aerobics",
    "CrossFit",
    "Zumba",
];